spring:
  application:
    name: auth-app
  datasource:
    url: jdbc:postgresql://dpg-ckkgcckl4vmc739smslg-a.singapore-postgres.render.com:5432/auth_app_89ja
    username: auth_app_89ja_user
    password: aA7mbTARxBnm0fc2RgX9iyiZWU7c0CMS
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
